qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY}"
  use_grpc: true

embedding:
  primary:
    provider: "gemini"
    model: "gemini-embedding-001"
    api_key: "${GEMINI_API_KEY}"
    dimensions: 768

# Issue Triage Agent Configuration
triage:
  enabled: true
  llm:
    provider: "gemini"
    model: "gemini-1.5-flash"
    api_key: "${GEMINI_API_KEY}"
  classifier:
    enabled: true
    min_confidence: 0.7
    labels:
      - name: "bug"
        keywords: ["error", "crash", "broken", "not working", "fails", "panic", "segfault"]
      - name: "enhancement"
        keywords: ["feature", "add", "improve", "request", "would be nice"]
      - name: "question"
        keywords: ["how to", "help", "?", "wondering", "usage"]
      - name: "documentation"
        keywords: ["docs", "readme", "typo", "help text", "man page"]
      - name: "platform/windows"
        keywords: ["windows", "powershell", "cmd.exe", "win32"]
      - name: "platform/macos"
        keywords: ["macos", "darwin", "brew", "homebrew"]
      - name: "platform/linux"
        keywords: ["linux", "ubuntu", "debian", "centos", "apt", "yum"]
  quality:
    enabled: true
    min_score: 0.5
    needs_info_label: "needs-info"
  duplicate:
    enabled: true
    auto_close_threshold: 0.95
    require_confirmation: false

defaults:
  similarity_threshold: 0.65
  max_similar_to_show: 5
  include_closed_issues: true
  closed_issue_weight: 0.9
  cross_repo_search: true
  comment_cooldown_hours: 1
  delayed_actions:
    enabled: true
    delay_hours: 24
    approve_reaction: "+1"
    cancel_reaction: "-1"
    execute_on_approve: false

repositories:
  - org: "similigh"
    repo: "nexusflow-cli"
    enabled: true
    similarity_threshold: 0.65
    transfer_rules:
      # Documentation issues go to docs
      - match:
          title_contains: ["documentation", "docs", "help text", "man page", "usage example"]
        target: "similigh/nexusflow-docs"
        priority: 1

      # Core server issues go to core
      - match:
          title_contains: ["server bug", "gateway", "memory leak", "TLS", "WebSocket", "plugin", "rate limit"]
        target: "similigh/nexusflow-core"
        priority: 2
      - match:
          body_contains: ["server crash", "gateway error", "connection pool", "runtime panic", "plugin system"]
        target: "similigh/nexusflow-core"
        priority: 3

      # VS Code issues go to vscode
      - match:
          title_contains: ["VS Code", "VSCode", "extension", "IntelliSense"]
        target: "similigh/nexusflow-vscode"
        priority: 4

      # SDK issues go to SDK
      - match:
          title_contains: ["SDK", "Python", "TypeScript", "Go client", "client library"]
        target: "similigh/nexusflow-sdk"
        priority: 5
      - match:
          body_contains: ["import nexusflow", "from nexusflow", "nexusflow.NewClient", "SDK"]
        target: "similigh/nexusflow-sdk"
        priority: 6

rate_limits:
  github_requests_per_second: 10
  embedding_requests_per_second: 5
  qdrant_requests_per_second: 50
